### ISSUE TITLE
Zenodo DOI Addition

### ISSUE THREAD

**Issue by apeltzer** [nf-core/dualrnaseq#8]
Please add the Zenodo DOI to the main README.md

[![DOI](https://zenodo.org/badge/309982089.svg)](https://zenodo.org/badge/latestdoi/309982089)

```
[![DOI](https://zenodo.org/badge/309982089.svg)](https://zenodo.org/badge/latestdoi/309982089)
```

**Comment by reganhayward** [comment]
All done
